version: '3.8'

services:
  php_app2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8087:80"
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  db1:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: backend_demo_1
      MYSQL_DATABASE: backend_todo
      MYSQL_USER: backend_demo_1
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin2:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db1
      MYSQL_ROOT_PASSWORD: backend_demo_1
    ports:
      - "8088:80"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
